/**
 * Domain types shared by backend and frontend.
 *
 * These mirror the Room entities in the POS app (`data/Entities.kt`). Any change
 * here must be mirrored there and vice versa — the sync contract depends on it.
 *
 * ## Money
 * Every `*Amount`, `price`, `total`, `subtotal`, `cash*` field is an INTEGER
 * number of VND. Never a float. See `money.ts`.
 *
 * ## Identity
 * `syncId` is a UUID generated by whichever side creates the record, and is the
 * key used across the wire. The POS keeps its own local integer primary key for
 * Room; the server never sees or trusts it. This makes every sync operation
 * idempotent: replaying the same push cannot create duplicates.
 */

import type { DiscountType } from './discount.ts';

export type { DiscountType };

export const PaymentMethod = {
  CASH: 'CASH',
  TRANSFER: 'TRANSFER',
  CARD: 'CARD',
} as const;
export type PaymentMethod = (typeof PaymentMethod)[keyof typeof PaymentMethod];

export const OrderStatus = {
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
} as const;
export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];

export const OrderType = {
  DINE_IN: 'DINE_IN',
  TAKE_AWAY: 'TAKE_AWAY',
} as const;
export type OrderType = (typeof OrderType)[keyof typeof OrderType];

export const ShiftStatus = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
} as const;
export type ShiftStatus = (typeof ShiftStatus)[keyof typeof ShiftStatus];

export const StaffRole = {
  CASHIER: 'CASHIER',
  MANAGER: 'MANAGER',
} as const;
export type StaffRole = (typeof StaffRole)[keyof typeof StaffRole];

// ---- Master data: server is the source of truth, POS pulls ------------------

export interface Product {
  syncId: string;
  name: string;
  /** Integer VND. */
  price: number;
  category: string;
  active: boolean;
  updatedAtMs: number;
}

/**
 * Staff record as delivered to a POS terminal.
 *
 * SECURITY: `pinHash`/`pinSalt` are included ONLY on the device-scoped pull
 * endpoint, because the POS must authenticate offline. They must never appear in
 * any browser-facing response. The web admin uses `StaffPublic` instead.
 */
export interface StaffCredential {
  syncId: string;
  name: string;
  role: StaffRole;
  /** Base64 PBKDF2-HMAC-SHA256 derivation. Never log this. */
  pinHash: string;
  /** Base64 16-byte salt. Never log this. */
  pinSalt: string;
  active: boolean;
  updatedAtMs: number;
}

/** Staff as shown in the web admin — no credential material. */
export interface StaffPublic {
  syncId: string;
  name: string;
  role: StaffRole;
  active: boolean;
  createdAtMs: number;
}

/**
 * A batch of single-use discount codes assigned to ONE terminal.
 *
 * Codes are partitioned per device on purpose: a code only ever exists on the
 * terminal it was issued to, so the POS can consume it offline inside its local
 * transaction and double-spend remains impossible without a network round trip.
 */
export interface DiscountCodeAssignment {
  syncId: string;
  code: string;
  campaignSyncId: string;
  campaignName: string;
  valueType: Extract<DiscountType, 'AMOUNT' | 'PERCENT'>;
  /** VND when AMOUNT, percent 1..100 when PERCENT. */
  value: number;
}

// ---- Transactional data: POS is the source of truth, POS pushes -------------

export interface OrderItemPush {
  syncId: string;
  productSyncId: string | null;
  /** Snapshot at sale time — deliberately not a join. */
  productName: string;
  /** Integer VND, snapshot at sale time. */
  unitPrice: number;
  quantity: number;
}

export interface OrderPush {
  syncId: string;
  /** Integer VND. subtotal - discountAmount === total must hold. */
  subtotal: number;
  discountAmount: number;
  total: number;
  discountType: DiscountType;
  discountInput: number;
  discountCode: string | null;
  orderType: OrderType;
  paymentMethod: PaymentMethod;
  cashReceived: number;
  changeAmount: number;
  status: OrderStatus;
  createdAtMs: number;
  shiftSyncId: string | null;
  staffSyncId: string | null;
  staffName: string | null;
  cancelledByStaffSyncId: string | null;
  cancelledAtMs: number | null;
  items: OrderItemPush[];
}

export interface ShiftPush {
  syncId: string;
  openedAtMs: number;
  closedAtMs: number | null;
  /** Integer VND. */
  openingCash: number;
  countedCash: number | null;
  expectedCash: number | null;
  cashDifference: number | null;
  /** Note-by-note evidence, e.g. "500000x2;100000x5". */
  cashBreakdown: string | null;
  status: ShiftStatus;
  staffSyncId: string | null;
  staffName: string | null;
  closedByStaffSyncId: string | null;
}

// ---- Sync envelopes ---------------------------------------------------------

/**
 * POS -> server. Everything the terminal recorded while it owned the data.
 * The terminal is identified by its bearer token alone (no deviceId field).
 */
export interface SyncPushRequest {
  /** Client clock, for drift diagnostics only — never used for ordering. */
  clientTimeMs: number;
  orders: OrderPush[];
  shifts: ShiftPush[];
}

export interface SyncRejection {
  /** syncId of the rejected record. */
  syncId: string;
  kind: 'order' | 'shift';
  reason: string;
}

export interface SyncPushResponse {
  /** syncIds the server has durably stored (includes already-known ones). */
  acceptedOrderIds: string[];
  acceptedShiftIds: string[];
  /** Records the server refused. The POS must keep these and surface them. */
  rejected: SyncRejection[];
  serverTimeMs: number;
}

/** Server -> POS. Master data plus this terminal's private code batch. */
export interface SyncPullResponse {
  products: Product[];
  staff: StaffCredential[];
  discountCodes: DiscountCodeAssignment[];
  serverTimeMs: number;
  /** Echoed back on the next pull so the server can send only what changed. */
  cursor: string;
}
